### PR TITLE
tBTC local development installation script

### PR DESCRIPTION
**Pull request by nkuba**
Added a set of scripts that can be used to install tBTC on a local development environment.

It is expected that [`keep-ecdsa` has been installed](https://github.com/keep-network/keep-ecdsa#install-script) as a prerequisite. 
To execute tBTC installation run:
```
./scripts/install.sh
```
Depends on: https://github.com/keep-network/tbtc/pull/633

### CODE REVIEW

**Comment by Shadowfiend** [comment]
I'm going to let @lukasz-zimnoch do the heavy review + merge here. High-level, this looks good, except for the fact that this much bash always makes me itchy :p

**Comment by pdyraga** [comment]
When executing, it failed on `2_deploy_contracts.js` with:
```
2_deploy_contracts.js
=====================

/usr/local/lib/node_modules/node/lib/node_modules/truffle/build/cli.bundled.js:132440
  throw new Error(
  ^

Error: Could not find artifacts for @summa-tx/relay-sol/contracts/OnDemandSPV from any sources
    at Resolver.require (/usr/local/lib/node_modules/node/lib/node_modules/truffle/build/webpack:/packages/resolver/index.js:25:1)
    at Object.require (/usr/local/lib/node_modules/node/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:167:1)
    at ResolverIntercept.require (/usr/local/lib/node_modules/node/lib/node_modules/truffle/build/webpack:/packages/migrate/resolverintercept.js:18:1)
    at /Users/piotr/go/src/github.com/keep-network/tbtc/solidity/migrations/2_deploy_contracts.js:26:31
    at Script.runInContext (vm.js:135:20)
    at Script.runInNewContext (vm.js:141:17)
    at Object.file (/usr/local/lib/node_modules/node/lib/node_modules/truffle/build/webpack:/packages/require/require.js:92:1)
    at Migration._load (/usr/local/lib/node_modules/node/lib/node_modules/truffle/build/webpack:/packages/migrate/migration.js:43:1)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
Truffle v5.1.18 (core: 5.1.18)
Node v11.15.0
```

I observed no problems with `npm install`, unlocking contracts, compiling them or with the initial migration.

**Comment by pdyraga** [comment]
Oh, I see https://github.com/keep-network/tbtc/pull/633. Let me merge `master` here first.

**Comment by liamzebedee** [comment]
🙌 cheers @nkuba!

**Pull request merged**
