### PR TITLE
Add SECURITY.adoc with vulnerability disclosure policy

### PR DESCRIPTION
**Pull request by Shadowfiend**
This outlines both the versions that are supported for vulnerabilities at this
time, as well as the requested process for disclosing vulnerabilities to the
team.

### CODE REVIEW

**Review by duydai91 — APPROVED** [review]

**Comment by duydai91** [comment]
Hi adm

**Review by duydai91 — APPROVED** [review]
I trust you very much, looking forward to good development

**Review by duydai91 — COMMENTED** [review]
Good,i hope
Be strong

**Comment by Shadowfiend** [comment]
Apparently you can't delete content after you've blocked a user :shrug:

**Review by mhluongo — APPROVED** [review]
:muscle: 

This is great, especially the example. It'll be good to clarify tiers and some other details of the bug bounty down the road.

**Review by paaqp — APPROVED** [review]

**Comment by paaqp** [comment]
It ma life

**Pull request merged**
